apiVersion: v1  # Specifies the API version and the resource type (Secret) in Kubernetes.
kind: Secret  # Defines the kind of resource; here, it's a Secret, which stores sensitive data.
metadata:
  name: secretcollection  # The name of the Secret.
type: Opaque  # Indicates the type of Secret, 'Opaque' is used for arbitrary user-defined data.
data:
  dbuser: cG9zdGdyZXM=           # Base64 encoded value of  (database username).
  dbpassword: U2hhaGFiYXpANzg2   # Base64 encoded value of  (database password).
  dbname: bGFwdG9wX2xvdW5nZQ==   # Base64 encoded value of  (database name).
